services:
  smarthome-api:
    image: smarthome-api:${VERSION:-latest}
    build:
      context: ./backend-dotnet
      dockerfile: Dockerfile
    ports:
    - "5033:80"
    - "5001:443"
    environment:
    - ASPNETCORE_ENVIRONMENT=Production # можно поменять на development
    - ASPNETCORE_URLS=http://+:80  # Добавьте эту строку
    - ConnectionStrings__IndustrialDatabase=Host=timescaledb;Database=industrial;Username=postgres;Password=industrial123
    - ConnectionStrings__Redis=redis-cache:6379
    - JwtSettings__SecretKey=${JWT_SECRET_KEY}
    depends_on:
      timescaledb:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    networks:
      - industrial_networks
    restart: unless-stopped
    
  # Кеш
  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
    - "6379:6379"
    networks:
      - industrial_networks
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  #База данных
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: industrial123
      POSTGRES_DB: industrial
      POSTGRES_USER: postgres
    volumes:
    - ~/docker/timescaledb/data:/var/lib/postgresql/data
  #  - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - industrial_networks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d industrial"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# === ДЕТАЛИЗАЦИЯ HEALTH CHECKS ===
# healthcheck позволяет Docker отслеживать состояние сервиса
# test - команда для проверки здоровья
# interval - периодичность проверки (10 секунд)
# timeout - максимальное время выполнения команды
# retries - количество неудачных попыток перед пометкой unhealthy
# start_period - время на первоначальный запуск сервиса
   
#Брокер сообщений
  rabbitmq_queue:
    image: rabbitmq:3-management
    container_name: rabbitmq_queue
    ports:
      - "5672:5672" # Standard AMQP port
      - "15672:15672" # Management UI port
      - "1883:1883"   # MQTT
      - "8883:8883"   # MQTT over SSL
      - "15675:15675" # MQTT WebSocket
      - "15676:15676" # MQTT WebSocket SSL
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
     
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./ssl:/etc/rabbitmq/ssl
    networks:
      - industrial_networks
    restart: unless-stopped

#  === ОБЪЯСНЕНИЕ СЕТЕВОЙ АРХИТЕКТУРЫ ===
# industrial-network: изолированная сеть для внутреннего взаимодействия
# Порты пробрасываются только для внешнего доступа к API, Grafana, Prometheus
# Внутренние сервисы общаются по именам (industrial-api, timescaledb и т.д.

#Экспортер Метрик
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    # extra_hosts:
    # - "host.docker.internal:172.17.0.1"
    networks:
      - industrial_networks
    restart: unless-stopped
 
#Визуализатор Метрик
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards:/etc/grafana/dashboard
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - industrial_networks
# Экспортер Radis
# redis-exporter:
#   image: oliver006/redis_exporter:latest
#   container_name: redis_exporter
#   environment:
#     - REDIS_ADDR=redis://redis-cache:6379
#   ports:
#     - "9121:9121"
#   networks:
#     - industrial_networks
#   restart: unless-stopped
#Экспортер с БД
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:industrial123@timescaledb:5432/industrial?sslmode=disable
    networks:
      - industrial_networks
  #Экспортер с Очереди сообщений
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    ports:
      - "9419:9419"
    environment:
      - RABBIT_URL=http://rabbitmq_queue:15672
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=admin
    networks:
      - industrial_networks
    #Алерт Менеджер
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - alertmanager_data:/alertmanager
      - ./config-alert.yml:/etc/alertmanager/config.yaml
    command:
      - '--config.file=/etc/alertmanager/config.yaml'
      - '--storage.path=/alertmanager'
    networks:
     - industrial_networks



volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
  rabbitmq_data: 
  timescaledb_data:
    driver: local

networks:
    industrial_networks:
         driver: bridge  
  